name: CompatHelper
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: PkgDerivativeFreeSolversadd("CompatHelper")
        run: julia -e 'using Pkg; PkgDerivativeFreeSolversadd("CompatHelper")'
      - name: CompatHelperDerivativeFreeSolversmain()
        env:
          GITHUB_TOKEN: ${{ secretsDerivativeFreeSolversGITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secretsDerivativeFreeSolversDOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelperDerivativeFreeSolversmain()'
