name: TagBot
on:
  issue_comment:
    types:
      - created
  workflow_dispatch:
jobs:
  TagBot:
    if: githubDerivativeFreeSolversevent_name == 'workflow_dispatch' || githubDerivativeFreeSolversactor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secretsDerivativeFreeSolversGITHUB_TOKEN }}
          ssh: ${{ secretsDerivativeFreeSolversDOCUMENTER_KEY }}
